name: Continuous Deployment

on:
  workflow_run:
    workflows: [Continuous Integration]
    types:
      - completed

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release
        run: echo "Triggering release"

  release:
    runs-on: ubuntu-latest
    needs: trigger-release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install semantic-release as dependency
        run: npm install semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
